version: 2.1
jobs:
  run_tests:
    docker:
      - image: circleci/node:18
    # environment:
    #   repo_token: jN0RLHMWq2HjgvYpWbkArx64CdE5Jfsy8
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: cd NODE_MONGO && npm install
      - run:
          name: Install npm dev dependencies
          command: cd NODE_MONGO && npm install mocha nyc chai-http chai
      - run:
          name: Run Unit Tests
          command: cd NODE_MONGO && npm run coverage
      # - run:
      #     name: Upload coverage to Coveralls
      #     command: cd NODE_MONGO && npx coveralls < coverage/lcov.info
workflows:
  build_tests:
    jobs:
      - run_tests
